### ISSUE TITLE
Options not visible

### ISSUE THREAD

**Issue by ricardobeat** [stevermeister/dutch-tax-income-calculator#10]
All the options (30% ruling, holiday allowance etc) used to be visible right next to the form, but now they are hidden under the hamburger menu even in Desktop, replaced by a ton of empty space. Maybe an issue with media queries?

Or if its intentional, I have to say the previous design made a lot more sense. All the content is on the left, and is obscured by the menu when you try to toggle any option.

![image](https://user-images.githubusercontent.com/97396/225043884-ae2ba4eb-1c5b-4c67-9c5b-17f933a4cf40.png)

**Comment by stevermeister** [comment]
the issue is already described here - https://github.com/stevermeister/dutch-tax-income-calculator/issues/4

now it had the highest priority. 
unfortunately, I'm not that HTML/media queries proficient to do it fast. 

you are welcome to contribute and make PR
