### ISSUE TITLE
calculator for 2024

### ISSUE THREAD

**Issue by Eugst** [stevermeister/dutch-tax-income-calculator#13]
Less than a month left to 2024. But there is no option to check taxes in 2024 yet. 
Could you add this option, please?

**Comment by stevermeister** [comment]
@Eugst thank you for raising the question! 

You are very welcome to suggest a PR for the core module here - https://github.com/stevermeister/dutch-tax-income-calculator-npm

Example of updating numbers you can find here - https://github.com/stevermeister/dutch-tax-income-calculator-npm/pull/28/files

Sorry, that for now, I don't have time to do it myself

**Comment by Eugst** [comment]
hey @stevermeister 
I wish to help, but I couldn't find the data for 2024

**Comment by stevermeister** [comment]
I believe here are the numbers - https://download.belastingdienst.nl/belastingdienst/docs/bijlage-nieuwsbrief-loonheffingen-2024-lh2091b41fd.pdf

**Comment by stevermeister** [comment]
and here you can find ones for **2023** (just to compare and find right ones for all the cases) - https://www.belastingdienst.nl/wps/wcm/connect/bldcontentnl/themaoverstijgend/brochures_en_publicaties/nieuwsbrief-loonheffingen-2023
