### ISSUE TITLE
No 2023/24 calculators on the domain?

### ISSUE THREAD

**Issue by dpashutskii** [stevermeister/dutch-tax-income-calculator#15]
Sorry, maybe it was moved somewhere else but as I can see https://thetax.nl/ only supports 2022 and previous years. Maybe something wasn't deployed to the prod?

Also, I remember the UI was a bit different, this one seems like an old one.

**Comment by stevermeister** [comment]
@guar47 it should not be the case, can you maybe cleanup the cache? 

![Screenshot 2024-02-16 at 13 43 03](https://github.com/stevermeister/dutch-tax-income-calculator/assets/1526680/de05b26c-58e9-42f3-abc6-4d134138915b)

**Comment by dpashutskii** [comment]
@stevermeister Lol. Cleaning up the cache helped, indeed. Thank you.
