### ISSUE TITLE
show (don't hide) side menu for the first run

### ISSUE THREAD

**Issue by stevermeister** [stevermeister/dutch-tax-income-calculator#4]
for new users or users of new UX, it's not always clear that there are also options to setup.

**Comment by jan-oratowski** [comment]
I agree with that.
It was quite confusing for me to fill in the value and have no way of toggling the 30% rule on and off.
Had to look around for a while to find the hamburger and the only reason I knew that I should look for it, was that I'd used the previous version.

In my opinion, on a desktop, it should always be visible (there is a lot of space for that). On mobile, maybe it should be hidden, but then there should be some kind of hint (notification, bubble, or whatever else) about that.
