### ISSUE TITLE
30% ruling - tax-free and taxable income do not equal total gross

### ISSUE THREAD

**Issue by eualexam** [stevermeister/dutch-tax-income-calculator#5]
Hello,

I'm having some trouble understanding the calculations, they don't seem to match the results I'm getting while doing a manual calculation.
<img width="1136" alt="Screenshot 2023-01-11 at 18 23 21" src="https://user-images.githubusercontent.com/56038358/212401974-65da7507-8266-4a74-a60c-1de6c50bd803.png">

Filters on: holiday allowance included and 30% ruling.

Amount tested: 80k gross per year.

Main results that don't match: taxable income, tax-free income, and implicitly, the final net salary.

Questions & comments based on manual calculation in the screenshot attached.

Thanks!

**Comment by stevermeister** [comment]
@eualexam thank you for adding your feedback! 
it will be be more convenient for others if you put in text (not image) all your calculations - that other can check by coping specific numbers
