### ISSUE TITLE
30% ruling issues

### ISSUE THREAD

**Issue by stockiller** [stevermeister/dutch-tax-income-calculator#6]
With the new version of the website, its not possible to specify what kind of 30% ruling someone is entitled to

<img width="440" alt="image" src="https://user-images.githubusercontent.com/60266962/214048711-6c124e6d-ad1c-4b7e-948d-0757ed208317.png">

Since the 30% ruling is only valid if the annual taxable salary is higher than ~41k , a person with master degree that has a lower salary, doesn't have the correct net value calculation because the annual taxable salary only needs to be higher than ~31k

**Comment by stevermeister** [comment]
@stockiller thank you for your report. 
the issue is already created here - https://github.com/stevermeister/dutch-tax-income-calculator/issues/3
you can provide there the details. 
not to have duplication I'll close this one
