### ISSUE TITLE
After reloading the home page options "Holiday allowance included", "66 years & older", "30% ruling" always change to Checked status

### ISSUE THREAD

**Issue by artur-godunov** [stevermeister/dutch-tax-income-calculator#9]
<img width="443" alt="Screenshot 2023-02-25 at 14 45 59" src="https://user-images.githubusercontent.com/83583609/221360322-28272ba1-a192-4f18-81ee-545b9ad4c26e.png">

**Possible solution:**

In _home.component.ts_ you can change
`params['allowance'] && this.allowance.setValue(params['allowance']);`
to
`
if (params['allowance']) {
  this.allowance.setValue(params['allowance'] === 'true');
}
`
and also change other same code which gets boolean value from url parameters.

**Comment by stevermeister** [comment]
@artur-godunov good catch! thank you for reporting and suggesting the solution. 

Maybe you can make a PR for it?

**Comment by stevermeister** [comment]
@artur-godunov should be fixed now. 
one more time thank you for the finding!
